### ISSUE TITLE
Footer is in the middle of the page in mobile view only. It should be fixed to the bottom

### ISSUE THREAD

**Issue by Abrosss** [Abrosss/Workspace#2]
![issues](https://user-images.githubusercontent.com/84074575/182834945-e76959d3-ffbb-48b5-a94e-7d9acd82532b.png)

**Comment by Akidane47** [comment]
May I work on it?

**Comment by Abrosss** [comment]
> May I work on it?

Yes of course. Assigned you!

**Comment by danielafriheart** [comment]
Can I work on this??

**Comment by davidmicahdaniels** [comment]
use flexbox

**Comment by Abrosss** [comment]
fixed
