### ISSUE TITLE
Add settings page (html/css)

### ISSUE THREAD

**Issue by Abrosss** [Abrosss/Workspace#7]
![settings](https://user-images.githubusercontent.com/84074575/184589858-96c5927b-2522-43d6-b4ce-f63a52ac7ef9.png)

**Comment by Jamesreally** [comment]
I like to take on this, kindly give a brief description of what you want on the settings page

**Comment by Abrosss** [comment]
> I like to take on this, kindly give a brief description of what you want on the settings page

Hello! Just 2 buttons Light/Dark like on the picture, the form, and save button. html/css only! Nevermind the sidebar and the nav. Please ask questions if you face any troubles! Thank you!

**Comment by Jamesreally** [comment]
Alright thanks, I will get back to you here if I need any clarification.
